seed: 3
data_directory: "/home/sarthakj/data/MultiEarth/multiearth2023-dataset-final/data"
dates_path: "/home/sarthakj/code/AI/projects/summers/summer_2024/AFRL/env_pred/preprocessing/data_split/DATES.npy"
train_data_path: "/home/sarthakj/code/AI/projects/summers/summer_2024/AFRL/env_pred/preprocessing/data_split/sent2_train_indexes.npy"
val_data_path: "/home/sarthakj/code/AI/projects/summers/summer_2024/AFRL/env_pred/preprocessing/data_split/sent2_val_indexes.npy"
test_data_path: "/home/sarthakj/code/AI/projects/summers/summer_2024/AFRL/env_pred/preprocessing/data_split/sent2_test_indexes.npy"
num_temporal_embeddings: 12
num_positional_embeddings: 37
num_epochs: 1000
batch_size: 15
learning_rate: 0.002
display_step: 1
prints_per_epoch: 20
accumulation_steps: 7
